In [1]:
pip install mloptima

Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install scikit-learn==1.1.1

Note: you may need to restart the kernel to use updated packages.


In [3]:
import coreml
import numpy as np
from coreml.integerprogramming import optimize

## Метод Гомори

In [3]:
def inputData():
      nX=int(input('Enter number of variables'))
      nY=int(input('Enter number of restrictions'))
      A = []
      for i in range(nY): 
        z=[int(j) for j in np.zeros(nY)]
        z[i]=1
        A.append(list(map(int, input('Enter coefficients of constraint variables by lines').split()))+z)
      A=np.array(A)
      B = np.array([int(i) for i in input('Enter free members of restrictions:').split()])
      C = np.array([int(i) for i in input('Enter coefficients of objective function (Without multiplying by -1):').split()]+[int(i) for i in np.zeros(nY)])
      basis = np.array([i for i in input('Enter basis variables names in right order:').split()])
      variables = np.array([i for i in input('Enter all variables names in right order:').split()])
      target_vars = set(np.array([i for i in input('Enter Names of needed variables:').split()]))
      extrema =str(input('Which extrema to find?("max";"min"):'))
      return A,B,C,basis,variables,target_vars,extrema

In [4]:
A,B,C,basis,variables,target_vars,extrema=inputData()

Enter number of variables3
Enter number of restrictions3
Enter coefficients of constraint variables by lines5 1 4
Enter coefficients of constraint variables by lines3 0 2
Enter coefficients of constraint variables by lines1 0 -3
Enter free members of restrictions:7 4 3
Enter coefficients of objective function (Without multiplying by -1):11 5 4
Enter basis variables names in right order:y1 y2 y3
Enter all variables names in right order:x1 x2 x3 y1 y2 y3
Enter Names of needed variables:x1 x2 x3
Which extrema to find?("max";"min"):max


In [5]:
optimize.gomori_method(A=A, B=B, C=C, basis=basis, variables=variables, 
                       target_vars=target_vars, extrema=extrema)

All coefficients in string Z are >= 0
[[ 5.  1.  4.  1.  0.  0.  7.]
 [ 3.  0.  2.  0.  1.  0.  4.]
 [ 1.  0. -3.  0.  0.  1.  3.]
 [14.  0. 16.  5.  0.  0. 35.]] ['x2' 'y2' 'y3']
F(X) = -35.0, X: x2=7.0


/Users/leotemirov/Downloads/ML_opt-master-6/coreml/integerprogramming/optimize.py:53: RuntimeWarning: divide by zero encountered in true_divide
  b_div_lead_col = M[:, -1][: len(basis)] / leading_column[: len(basis)]


(array([[ 5.,  1.,  4.,  1.,  0.,  0.,  7.],
        [ 3.,  0.,  2.,  0.,  1.,  0.,  4.],
        [ 1.,  0., -3.,  0.,  0.,  1.,  3.],
        [14.,  0., 16.,  5.,  0.,  0., 35.]]),
 array(['x2', 'y2', 'y3'], dtype='<U2'),
 array(['x1', 'x2', 'x3', 'y1', 'y2', 'y3'], dtype='<U2'))

In [6]:
A,B,C,basis,variables,target_vars,extrema=inputData()
optimize.gomori_method(A=A, B=B, C=C, basis=basis, variables=variables, 
                       target_vars=target_vars, extrema=extrema)

Enter number of variables3
Enter number of restrictions3
Enter coefficients of constraint variables by lines3 2 8
Enter coefficients of constraint variables by lines2 0 1
Enter coefficients of constraint variables by lines3 3 1
Enter free members of restrictions:11 5 13
Enter coefficients of objective function (Without multiplying by -1):11 5 4
Enter basis variables names in right order:y1 y2 y3
Enter all variables names in right order:x1 x2 x3 y1 y2 y3
Enter Names of needed variables:x1 x2 x3
Which extrema to find?("max";"min"):max
All coefficients in string Z are >= 0
[[  0.     1.     3.25   0.5   -0.75   0.     1.75]
 [  1.     0.     0.5    0.     0.5    0.     2.5 ]
 [  0.     0.   -10.25  -1.5    0.75   1.     0.25]
 [  0.     0.    17.75   2.5    1.75   0.    36.25]] ['x2' 'x1' 'y3']
F(X) = -17.0, X: x2=-8.0  x1=1.0  x3=3.0


(array([[  0.,   1.,   0.,  -6.,  -4.,   0.,  13.,  -8.],
        [  1.,   0.,   0.,  -1.,   0.,   0.,   2.,   1.],
        [  0.,   0.,   0.,  19.,  11.,   1., -41.,  31.],
        [  0.,   0.,   1.,   2.,   1.,   0.,  -4.,   3.],
        [  0.,   0.,   0.,  33.,  16.,   0., -71.,  17.]]),
 array(['x2', 'x1', 'y3', 'x3'], dtype='<U2'),
 array(['x1', 'x2', 'x3', 'y1', 'y2', 'y3', 't1'], dtype='<U2'))

## Симплекс метод

In [7]:
A,B,C,basis,variables,target_vars,extrema=inputData()

Enter number of variables3
Enter number of restrictions3
Enter coefficients of constraint variables by lines3 2 8
Enter coefficients of constraint variables by lines2 0 1
Enter coefficients of constraint variables by lines3 3 1
Enter free members of restrictions:11 5 13
Enter coefficients of objective function (Without multiplying by -1):11 5 4
Enter basis variables names in right order:y1 y2 y3
Enter all variables names in right order:x1 x2 x3 y1 y2 y3
Enter Names of needed variables:x1 x2 x3
Which extrema to find?("max";"min"):max


In [9]:
optimize.make_simplex(A=A, B=B, C=C, basis=basis, variables=variables,  extrema=extrema)

All coefficients in string Z are >= 0
[[  0.     1.     3.25   0.5   -0.75   0.     1.75]
 [  1.     0.     0.5    0.     0.5    0.     2.5 ]
 [  0.     0.   -10.25  -1.5    0.75   1.     0.25]
 [  0.     0.    17.75   2.5    1.75   0.    36.25]] ['x2' 'x1' 'y3']


(array([[  0.  ,   1.  ,   3.25,   0.5 ,  -0.75,   0.  ,   1.75],
        [  1.  ,   0.  ,   0.5 ,   0.  ,   0.5 ,   0.  ,   2.5 ],
        [  0.  ,   0.  , -10.25,  -1.5 ,   0.75,   1.  ,   0.25],
        [  0.  ,   0.  ,  17.75,   2.5 ,   1.75,   0.  ,  36.25]]),
 array(['x2', 'x1', 'y3'], dtype='<U2'),
 array(['x1', 'x2', 'x3', 'y1', 'y2', 'y3'], dtype='<U2'))

In [10]:
A,B,C,basis,variables,target_vars,extrema=inputData()

Enter number of variables3
Enter number of restrictions3
Enter coefficients of constraint variables by lines5 1 4 
Enter coefficients of constraint variables by lines3 0 2
Enter coefficients of constraint variables by lines1 0 -3
Enter free members of restrictions:7 4 3
Enter coefficients of objective function (Without multiplying by -1):11 5 4
Enter basis variables names in right order:y1 y2 y3
Enter all variables names in right order:x1 x2 x3 y1 y2 y3
Enter Names of needed variables:x1 x2 x3
Which extrema to find?("max";"min"):max


In [11]:
optimize.make_simplex(A=A, B=B, C=C, basis=basis, variables=variables,  extrema=extrema)

All coefficients in string Z are >= 0
[[ 5.  1.  4.  1.  0.  0.  7.]
 [ 3.  0.  2.  0.  1.  0.  4.]
 [ 1.  0. -3.  0.  0.  1.  3.]
 [14.  0. 16.  5.  0.  0. 35.]] ['x2' 'y2' 'y3']


(array([[ 5.,  1.,  4.,  1.,  0.,  0.,  7.],
        [ 3.,  0.,  2.,  0.,  1.,  0.,  4.],
        [ 1.,  0., -3.,  0.,  0.,  1.,  3.],
        [14.,  0., 16.,  5.,  0.,  0., 35.]]),
 array(['x2', 'y2', 'y3'], dtype='<U2'),
 array(['x1', 'x2', 'x3', 'y1', 'y2', 'y3'], dtype='<U2'))

### Вывод

Протестировав реализацию данных методов, можно выявить их главный минус: нельзя указать неотрицательность, из-за этого можно только проверять примеры, которые действуют на всю плоскость, также было бы замечательно, если сделать функцию для удобного ввода. В остальном все работает быстро и корректно.