<a href="https://colab.research.google.com/github/M1croZavr/ML_opt/blob/development/User_interface_notebook_integerprogramming_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install mloptima

  Preparing metadata (setup.py) ... done
  Created wheel for mloptima: filename=mloptima-0.0.1-py3-none-any.whl size=33743 sha256=47d9ad9585950cf8f96e6f2de621bddf5fc6644157fb24d14eb2dc0f1e59bd7f
  Stored in directory: /root/.cache/pip/wheels/a1/99/19/347e881e4c186860f9f1c4e8ffc0f8c490f773b0a0ac91b959
Successfully built mloptima


In [2]:
!pip install scikit-learn==1.1.1

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 30.4/30.4 MB 37.2 MB/s eta 0:00:00
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.2.2
    Uninstalling scikit-learn-1.2.2:
      Successfully uninstalled scikit-learn-1.2.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bigframes 0.15.0 requires scikit-learn>=1.2.2, but you have scikit-learn 1.1.1 which is incompatible.


In [3]:
import coreml
import numpy as np

In [4]:
from coreml.integerprogramming import optimize

In [ ]:
# Метод Гомори

def inputData():
  nX=int(input('Enter number of variables'))
  nY=int(input('Enter number of restrictions'))
  A = []
  for i in range(nY):
    z=[int(j) for j in np.zeros(nY)]
    z[i]=1
    A.append(list(map(int, input('Enter coefficients of constraint variables by lines').split()))+z)
  A=np.array(A)
  B = np.array([int(i) for i in input('Enter free members of restrictions:').split()])
  C = np.array([int(i) for i in input('Enter coefficients of objective function (Without multiplying by -1):').split()]+[int(i) for i in np.zeros(nY)])
  basis = np.array([i for i in input('Enter basis variables names in right order:').split()])
  variables = np.array([i for i in input('Enter all variables names in right order:').split()])
  target_vars = set(np.array([i for i in input('Enter Names of needed variables:').split()]))
  extrema =str(input('Which extrema to find?("max";"min"):'))
  return A,B,C,basis,variables,target_vars,extrema

In [ ]:
A,B,C,basis,variables,target_vars,extrema=inputData()
print(A,B,C,basis,variables,target_vars,extrema)

Enter number of variables3
Enter number of restrictions3
Enter coefficients of constraint variables by lines1 2 3
Enter coefficients of constraint variables by lines4 3 2
Enter coefficients of constraint variables by lines3 1 1
Enter free members of restrictions:35 45 40
Enter coefficients of objective function (Without multiplying by -1):4 5 6
Enter basis variables names in right order:y1 y2 y3
Enter all variables names in right order:x1 x2 x3 y1 y2 y3
Enter Names of needed variables:x1 x2 x3
Which extrema to find?("max";"min"):max
[[1 2 3 1 0 0]
 [4 3 2 0 1 0]
 [3 1 1 0 0 1]] [35 45 40] [4 5 6 0 0 0] ['y1' 'y2' 'y3'] ['x1' 'x2' 'x3' 'y1' 'y2' 'y3'] {'x2', 'x3', 'x1'} max


In [ ]:
optimize.gomori_method(A, B, C, basis, variables, target_vars=target_vars,extrema=extrema)

All coefficients in string Z are >= 0
[[ 0.   0.5  1.   0.4 -0.1  0.   9.5]
 [ 1.   0.5  0.  -0.2  0.3  0.   6.5]
 [ 0.  -1.   0.   0.2 -0.8  1.  11. ]
 [ 0.   0.   0.   1.6  0.6  0.  83. ]] ['x3' 'x1' 'y3']
F(X) = 83.0, X: x3=9.0  x1=6.0  x2=1.0


(array([[  0. ,   0. ,   1. ,   0. ,  -1. ,   0. ,   1. ,   9. ],
        [  1. ,   0. ,   0. ,  -0.6,  -0.6,   0. ,   1. ,   6. ],
        [  0. ,   0. ,   0. ,   1. ,   1. ,   1. ,  -2. ,  12. ],
        [  0. ,   1. ,   0. ,   0.8,   1.8,   0. ,  -2. ,   1. ],
        [  0. ,   0. ,   0. ,  -1.6,  -0.6,   0. ,  -0. , -83. ]]),
 array(['x3', 'x1', 'y3', 'x2'], dtype='<U2'),
 array(['x1', 'x2', 'x3', 'y1', 'y2', 'y3', 't1'], dtype='<U2'))